require('lua.plugins')
require('lua.plugs.default')
require('lua.plugs.blinkcmp')
require('lua.plugs.miniai')
require('lua.plugs.minisurround')
require('lua.lsps')
require('lua.config')
require('lua.keymaps')
